apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rfy3fo3z9-java-springboot
  janus-idp.io/tekton: rfy3fo3z9-java-springboot
  backstage.io/kubernetes-id: rfy3fo3z9-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rfy3fo3z9-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
